---
defaults: &defaults
  working_directory: ~/cli
  docker:
    - image: dickeyxxx/cli-engine-docker:v1.3.1

version: 2
executorType: docker
jobs:
  build:
    <<: *defaults
    steps:
      - type: checkout
      - type: cache-restore
        key: cli
      - type: shell
        command: |
          set -exu
          yarn config set registry https://cli-npm.heroku.com
          yarn install --pure-lockfile
          yarn check
          # build dev only if it is a git checkout
          if [ "${CIRCLE_BRANCH}" == "dev" ] && \
             [ ! -d ~/cli/node_modules/cli-engine/lib ]; then
            cd ~/cli/node_modules/cli-engine && yarn && cd ~/cli
          fi
          ./bin/run version
          ./bin/run help
      - type: cache-save
        key: cli
        paths:
          - /usr/local/share/.cache/yarn
      - type: deploy
        shell: /bin/bash
        command: |
          set -e
          echo $HEROKU_DEB_KEY | base64 -d | gpg --import
          set -ex
          ./scripts/release-wrapper deb
      - type: shell
        command: |
          set -ex
          ./scripts/copy-windows-files x64
          ./scripts/copy-windows-files x86
      - persist_to_workspace:
          root: .
          paths:
            - tmp/build/windows-x64.tar.gz
            - tmp/build/windows-x86.tar.gz
  release_windows_x64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/cli
      - run: |
          set -ex
          ./scripts/release-wrapper -a x64 windows
  release_windows_x86:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/cli
      - run: |
          set -ex
          ./scripts/release-windows -a x86 windows
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release_windows_x64:
          requires:
            - build
      - release_windows_x86:
          requires:
            - build
